env_id: FlappyBird-v0
n_episodes: 20  # eval on this many episodes
max_episode_steps: 10_000
seed: 0  # different from training seed
seed_fixed: false  # whether to fix the seed for each episode
stochastic: false  # whether to use stochastic policy
