env_id: FlappyBird-v0
n_episodes: 50_000
max_episode_steps: 10_000
gamma: 0.99
learning_rate: 1e-4
target_learning_rate: 1e-6
entropy_coeff: 0.01
seed: 42
load_model_path:  # loads this model and continues training when specified
save_model_path: models/flappybird_policy_neps50k.pt  # path to save the model
print_every: 250  # print after this many episodes
record_every: 5000  # record video after this many episodes
