env_id: FlappyBird-v0
n_episodes: 5_000
max_episode_steps: 10_000
gamma: 0.95
entropy_coeff: 0.01
learning_rate: 1e-2
target_learning_rate: 1e-4
batch_size: 0  # 0 to disable gradient accumulation
max_grad_norm: 0.0  # 0.0 to disable gradient clipping
seed: 42
load_model_path:  # loads this model and continues training when specified
save_model_path: # models/flappybird_policy_e50k_g.95_llr2.pt  # path to save the model
print_every: 250  # print after this many episodes
record_every: 1000  # record video after this many episodes
