env_id: FlappyBird-v0
n_episodes: 20_000
max_episode_steps: 10_000
gamma: 0.99
learning_rate: 1e-4
entropy_coeff: 0.01
seed: 42
load_model_path:  # loads this model and continues training when specified
save_model_path: flappybird_policy.pt  # path to save the model
print_every: 250  # print after this many episodes
